# Generated by Django 6.1.1 on 2026-09-05 06:22

import devices.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('plant_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('device_name', models.CharField(max_length=150)),
                ('qr_code_token', models.CharField(default=devices.models.generate_qr_token, editable=False, max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceConfig',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('webhook_url', models.URLField(blank=True, default='')),
                ('api_endpoint', models.URLField(blank=True, default='')),
                ('custom_settings', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='devices.device')),
            ],
        ),
    ]
