# Generated by Django 5.2.17 on 2026-09-09 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_id', models.CharField(default='pratham_plant_01', max_length=100, unique=True)),
                ('device_token', models.CharField(max_length=255)),
                ('is_online', models.BooleanField(default=False)),
                ('power_state', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=10)),
                ('message', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='core.device')),
            ],
        ),
        migrations.CreateModel(
            name='TouchAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('single', 'Single Tap'), ('double', 'Double Tap')], default='single', max_length=20)),
                ('text', models.CharField(default='Hi I am Tulsi', max_length=100)),
                ('track_id', models.IntegerField(default=1)),
                ('expression', models.CharField(default='happy', max_length=20)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='touch_actions', to='core.device')),
            ],
        ),
    ]
