# Generated by Django 5.2.17 on 2026-09-16 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_document_file_alter_document_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiagent',
            name='ai_model_name',
            field=models.CharField(default='gemini-3.6-flash', max_length=50),
        ),
    ]
