# Generated by Django 5.2.17 on 2026-09-16 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_aiagent_ai_model_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_quiz_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='device',
            name='quiz_topic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='PlantChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_text', models.TextField(db_index=True)),
                ('ai_response', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_history', to='core.device')),
            ],
        ),
    ]
