# Generated by Django 5.2.17 on 2026-09-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_device_is_quiz_active_device_quiz_topic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_paired',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='device',
            name='mac_address',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
