# Generated by Django 5.2.17 on 2026-10-01 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_device_owner_admin_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebase',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.userprofile'),
        ),
    ]
